### ISSUE TITLE
Issues in Node tests

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1306]
Here some issues in Node tests:

- [ ] CI failing due to aborted `PRODUCER_PAUSE` channel request: https://github.com/versatica/mediasoup/actions/runs/7448459449/job/20262892577?pr=1305
- [ ] `npm run test:node -- --testPathPattern test-ActiveSpeakerObserver` fails with:
  ```
  Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  PROCESSWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-ActiveSpeakerObserver.ts:26:31
      at node/src/test/test-ActiveSpeakerObserver.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-ActiveSpeakerObserver.ts:4:12)
      at Object.<anonymous> (node/src/test/test-ActiveSpeakerObserver.ts:25:23)


  ●  PIPEWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

          at Array.reduce (<anonymous>)
      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-ActiveSpeakerObserver.ts:26:31
      at node/src/test/test-ActiveSpeakerObserver.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-ActiveSpeakerObserver.ts:4:12)
      at Object.<anonymous> (node/src/test/test-ActiveSpeakerObserver.ts:25:23)
  ```
- [ ] `npm run test:node -- --testPathPattern "test-PipeTransport.ts"` fails with:
  ```
  Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  PROCESSWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-PipeTransport.ts:171:32
      at node/src/test/test-PipeTransport.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-PipeTransport.ts:4:12)
      at Object.<anonymous> (node/src/test/test-PipeTransport.ts:170:23)


  ●  PIPEWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

          at Array.reduce (<anonymous>)
      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-PipeTransport.ts:171:32
      at node/src/test/test-PipeTransport.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-PipeTransport.ts:4:12)
      at Object.<anonymous> (node/src/test/test-PipeTransport.ts:170:23)
  ```

Probably many similar ones if we run each test file separately.

NOTE: Yes, I added `--detectOpenHandles` to `jest` command, but it should work fine.

**Comment by ibc** [comment]
NOTE: In tests above I'm doing this change to avoid more open handlers when a test file completes:

```diff
diff --git a/node/src/Channel.ts b/node/src/Channel.ts
index 7e1c71961..abb2f0468 100644
--- a/node/src/Channel.ts
+++ b/node/src/Channel.ts
@@ -227,16 +227,6 @@ export class Channel extends EnhancedEventEmitter {
 		this.#producerSocket.removeAllListeners('end');
 		this.#producerSocket.removeAllListeners('error');
 		this.#producerSocket.on('error', () => {});
-
-		// Destroy the socket after a while to allow pending incoming messages.
-		setTimeout(() => {
-			try {
-				this.#producerSocket.destroy();
-			} catch (error) {}
-			try {
-				this.#consumerSocket.destroy();
-			} catch (error) {}
-		}, 200);
 	}
```

**Comment by nazar-pc** [comment]
> NOTE: In tests above I'm doing this change to avoid more open handlers when a test file completes

I strongly dislike timeouts like that. They are not reliable and will definitely fail at some point.

**Comment by ibc** [comment]
> > NOTE: In tests above I'm doing this change to avoid more open handlers when a test file completes
> 
> I strongly dislike timeouts like that. They are not reliable and will definitely fail at some point.

Yes. It was the only one in the code.
