### ISSUE TITLE
Should not crash if no more available ports

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#222]
This must be confirmed, but it seems that, if there are no more available RTP ports, the `mediasoup-worker` process crashes. Not sure if this is intentional. AFAIR it's not. Instead, the JS promise should just be rejected.

```
2018-11-12T17:31:15.228Z mediasoup:ERROR:mediasoup-worker [id:zuggrvev#9] RTC::UdpSocket::GetRandomPort() | throwing MediaSoupError | no more available ports for IP 'X.X.X.X'
2018-11-12T17:31:15.230Z mediasoup:ERROR:mediasoup-worker [id:zuggrvev#9] RTC::WebRtcTransport::WebRtcTransport() | error adding IPv4 UDP socket: no more available ports for IP 'X.X.X.X'
2018-11-12T17:31:15.230Z mediasoup:ERROR:mediasoup-worker [id:zuggrvev#9] RTC::WebRtcTransport::WebRtcTransport() | throwing MediaSoupError | could not open any IP:port
2018-11-12T17:31:15.411Z mediasoup:ERROR:Worker child process exited [id:zuggrvev#9, code:null, signal:SIGSEGV]
2018-11-12T17:31:15.541Z mediasoup:ERROR:Peer "router.createWebRtcTransport" request failed: InvalidStateError: Channel closed
2018-11-12T17:31:15.546Z mediasoup:ERROR:Peer receiveRequest() failed [method:createTransport]: InvalidStateError: Channel closed at klass (/home/ubuntu/mediasoup-demo-cosmo/server/node_modules/mediasoup/lib/errors.js:7:4) at Object.close (/home/ubuntu/mediasoup-demo-cosmo/server/node_modules/mediasoup/lib/Channel.js:247:14) at Channel.close (/home/ubuntu/mediasoup-demo-cosmo/server/node_modules/mediasoup/lib/Channel.js:170:9) at Worker.close (/home/ubuntu/mediasoup-demo-cosmo/server/node_modules/mediasoup/lib/Worker.js:132:17) at ChildProcess.Worker._child.on (/home/ubuntu/mediasoup-demo-cosmo/server/node_modules/mediasoup/lib/Worker.js:101:9) at emitTwo (events.js:106:13) at ChildProcess.emit (events.js:191:7) at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

**Comment by ibc** [comment]
Better logs showing an assertion error in libuv that produces the real crash:

```
  mediasoup:Channel request() [method:router.createWebRtcTransport, id:60685604] +660ms
  mediasoup:ERROR:mediasoup-worker [id:oqagohae#1] RTC::UdpSocket::GetRandomPort() | throwing MediaSoupError | no more available ports for IP '192.168.1.36' +0ms
  mediasoup:ERROR:mediasoup-worker [id:oqagohae#1] RTC::WebRtcTransport::WebRtcTransport() | error adding IPv4 UDP socket: no more available ports for IP '192.168.1.36' +0ms
  mediasoup:ERROR:mediasoup-worker [id:oqagohae#1] RTC::WebRtcTransport::WebRtcTransport() | throwing MediaSoupError | could not open any IP:port +1ms
mediasoup-worker's stderr: Assertion failed: (!uv__is_closing(handle)), function uv_close, file ../deps/libuv/src/unix/core.c, line 117.
  mediasoup:Channel channel ended by the other side +5ms
  mediasoup:ERROR:Worker child process exited [id:oqagohae#1, code:null, signal:SIGABRT]
```

**Comment by ibc** [comment]
Ok, the problem is the following:

* When there are no more ports available, the `WebRtcTransport` constructor fails so it calls `delete this` and, **after that**, it throws an exception.
* The `~WebRtcTransport` destructor is called and then the parent `~Transport` destructor is called.
* The `~Transport` destructor destroys the RTCP timer by calling `this->rtcpTimer->Destroy()`.
* After the destructors are called, the `WebRtcTransport` constructor throws an exception.
* Somehow, this exception causes that the `~Transport` destructor is called again, so it calls `this->rtcpTimer->Destroy()` again and here the obvious crash (the timer was already deleted).

Some related info:

https://isocpp.org/wiki/faq/exceptions#selfcleaning-members

**Comment by ibc** [comment]
So, theoretically, when a C++ class constructor throws an exception, its destructor is **NOT** called. The problem we have is that, after throwing the exception in the `WebRtcTransport` constructor, the destructor of its parent class `Transport` is being called! But it was already called before when calling `delete this` in the `WebRtcTransport` constructor.

**Comment by ibc** [comment]
@jmillan this will also affect the `PlainRtpTransport` class. In fact, it will leak if for any reason `SetRemoteParameters()` fails in the constructor.
