### ISSUE TITLE
Add clang-fuzzer

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#239]
As the tutorial below explains, this need to run with a `fuzzer` capable `clang`, so Linux or a Docker image is required. Working on this in the [fuzzer](https://github.com/versatica/mediasoup/tree/fuzzer) branch.

The idea is to "fuzz" all the mediasoup C++ parsers and functions that receive a buffer and a length.

Work to do:

* [x] Make `worker/scripts/get-dep.sh clang-fuzzer` get the corresponding clang binary + libs.
   * NOTE: Due to it big size, `worker/deps/clang-fuzzer` is "gitignored".
* [x] Add a "mediasoup-worker-fuzzer" target in `mediasoup-worker.gyp` that must be compiled with a `fuzzer` capable `clang`.
* [x] Add `Makefile` targets for building the fuzzer target (`make fuzzer`) and tu execute it with optional fuzzer options (`make fuzzer-run`).
* [ ] Allow setting `CFLAGS`, etc, environment variables when running `make fuzzer`.
   * This seems to be a requirement to enabling mediasoup fuzzing in [OSS-Fuzz](https://github.com/google/oss-fuzz).
   * However it's hard to figure out how to make GYP use the env `CFLAGS`.
* [x] Fill the `worker/fuzzer/fuzzer.cpp` file (it is a [fuzzer target](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md#hello-world-fuzzer)) with all the possible mediasoup calls that receive a `data` pointer and a `length` (ICE, RTP, RTCP parsers).
* [x] Complete the `worker/fuzzer/fuzzer.cpp` file with more tests specific to STUN, RTP and RTCP. We could even ru a libuv loop and test UDP/TCP.
* [x] Add a Docker image (Ubuntu 16.04) with a `fuzzer` capable `clang` to play with fuzzer in OSX.
* [x] Add `Makefile` targets for building and running the Docker image.

## References

* [libFuzzer documentation](http://llvm.org/docs/LibFuzzer.html)
* [libFuzzer Tutorial](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md)
* [webrtcH4cKS ~ Lets get better at fuzzing in 2019](https://webrtchacks.com/lets-get-better-at-fuzzing-in-2019-heres-how/):  By @fippo.
* [OSS-Fuzz](https://github.com/google/oss-fuzz):  Continuous fuzzing of open source software ("fuzz for me").

**Comment by ibc** [comment]
Mostly done in the `fuzzer` branch! The only missing part is the `worker/fuzzer/fuzzer.cpp` content itself (see bullets above).

**Comment by fippo** [comment]
you might want to use a seed corpus from https://chromium.googlesource.com/external/webrtc/+/master/test/fuzzers/corpora/

**Comment by ibc** [comment]
Will do.

**Comment by ibc** [comment]
Corpus stuff added here: 4fb1400f376a900768a3ef25a663b82b676f8098

**Comment by ibc** [comment]
Oh cool:

```
#13169	NEW    cov: 839 ft: 2928 corp: 166/25Kb lim: 4 exec/s: 4389 rss: 54Mb L: 587/592 MS: 2 ChangeASCIIInt-CopyPart-
=================================================================
==9==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200009f95c at pc 0x000000a3afc0 bp 0x7ffe893e2ed0 sp 0x7ffe893e2ec8
READ of size 1 at 0x60200009f95c thread T0
    #0 0xa3afbf in RTC::RTCP::SdesItem::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:40:38
    #1 0xa3ce44 in RTC::RTCP::SdesChunk::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:128:22
    #2 0xa3e08e in RTC::RTCP::SdesPacket::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:193:24
    #3 0xa2610e in RTC::RTCP::Packet::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Packet.cpp:103:17
    #4 0xb4946c in fuzz(unsigned char const*, unsigned long) /mediasoup/worker/out/../fuzzer/fuzzer.cpp:44:26
    #5 0xb4970a in LLVMFuzzerTestOneInput /mediasoup/worker/out/../fuzzer/fuzzer.cpp:63:2
    #6 0x45f47a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:576:15
    #7 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #8 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #9 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #10 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #11 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7f5469ecf82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x434a28 in _start (/mediasoup/worker/out/Release/mediasoup-worker-fuzzer+0x434a28)

0x60200009f95c is located 0 bytes to the right of 12-byte region [0x60200009f950,0x60200009f95c)
allocated by thread T0 here:
    #0 0x5951b2 in operator new[](unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:109:3
    #1 0x45f361 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:563:23
    #2 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #3 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #4 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #5 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #6 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #7 0x7f5469ecf82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:40:38 in RTC::RTCP::SdesItem::Parse(unsigned char const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c048000bed0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c048000bee0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c048000bef0: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c048000bf00: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c048000bf10: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
=>0x0c048000bf20: fa fa fd fd fa fa fd fd fa fa 00[04]fa fa 00 00
  0x0c048000bf30: fa fa 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
```

**Comment by ibc** [comment]
@jmillan here the bug:

```c++
		SdesItem* SdesItem::Parse(const uint8_t* data, size_t len)
		{
			MS_TRACE();

			// Get the header.
			auto* header = const_cast<Header*>(reinterpret_cast<const Header*>(data));

			// data size must be >= header + length value.
			if (sizeof(uint8_t) * 2 + header->length > len)
			{
				MS_WARN_TAG(rtcp, "not enough space for SDES item, discarded");

				return nullptr;
			}
```

It assumes that `data + len` can hold a `Header` struct, but it's not true if `len` is less than `sizeof(Header)`. So when calling this `SdesItem::Parse()` function from line 128 it crashes:

```c++
while (len > offset)
{
	SdesItem* item = SdesItem::Parse(data + offset, len - offset);
```

**Comment by ibc** [comment]
Moving this issue to #240 (and deleting related comments above).

**Comment by ibc** [comment]
I don't understand why `RTC::RTCP::Sdes::Parse() | not enough space for SDES item, discarded` is logged at all.

```c++
MS_WARN_TAG(rtcp, "not enough space for SDES item, discarded");
```

In `fuzzer/fuzzer.cpp` we are not enabling any `logTag` so `Settings::configuration.Settings::configuration.logTags.rtcp` should be `false` (default value).

**Comment by ibc** [comment]
Oh! `#define MS_LOG_DEV` was enabled in `Sdes.cpp`!!! Fixing it in the "fuzzer" branch.

**Comment by ibc** [comment]
The macro was also enabled in:

```bash
ibc at ibc-macbook in ~/src/mediasoup/worker/src on fuzzer*
$ ack "#define MS_LOG_DEV" | grep -v "//"
RTC/RTCP/ReceiverReport.cpp:2:#define MS_LOG_DEV
RTC/RTCP/SenderReport.cpp:2:#define MS_LOG_DEV
```

Fixed.
