### ISSUE TITLE
heap-buffer-overflow in RTCP::SdesItem::Parse()

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#240]
* mediasoup 2.5.6

```
#13169	NEW    cov: 839 ft: 2928 corp: 166/25Kb lim: 4 exec/s: 4389 rss: 54Mb L: 587/592 MS: 2 ChangeASCIIInt-CopyPart-
=================================================================
==9==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200009f95c at pc 0x000000a3afc0 bp 0x7ffe893e2ed0 sp 0x7ffe893e2ec8
READ of size 1 at 0x60200009f95c thread T0
    #0 0xa3afbf in RTC::RTCP::SdesItem::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:40:38
    #1 0xa3ce44 in RTC::RTCP::SdesChunk::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:128:22
    #2 0xa3e08e in RTC::RTCP::SdesPacket::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:193:24
    #3 0xa2610e in RTC::RTCP::Packet::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Packet.cpp:103:17
    #4 0xb4946c in fuzz(unsigned char const*, unsigned long) /mediasoup/worker/out/../fuzzer/fuzzer.cpp:44:26
    #5 0xb4970a in LLVMFuzzerTestOneInput /mediasoup/worker/out/../fuzzer/fuzzer.cpp:63:2
    #6 0x45f47a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:576:15
    #7 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #8 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #9 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #10 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #11 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7f5469ecf82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x434a28 in _start (/mediasoup/worker/out/Release/mediasoup-worker-fuzzer+0x434a28)

0x60200009f95c is located 0 bytes to the right of 12-byte region [0x60200009f950,0x60200009f95c)
allocated by thread T0 here:
    #0 0x5951b2 in operator new[](unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:109:3
    #1 0x45f361 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:563:23
    #2 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #3 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #4 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #5 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #6 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #7 0x7f5469ecf82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /mediasoup/worker/out/../src/RTC/RTCP/Sdes.cpp:40:38 in RTC::RTCP::SdesItem::Parse(unsigned char const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c048000bed0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c048000bee0: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c048000bef0: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c048000bf00: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c048000bf10: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
=>0x0c048000bf20: fa fa fd fd fa fa fd fd fa fa 00[04]fa fa 00 00
  0x0c048000bf30: fa fa 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000bf70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
```

@jmillan here the bug:

```c++
		SdesItem* SdesItem::Parse(const uint8_t* data, size_t len)
		{
			MS_TRACE();

			// Get the header.
			auto* header = const_cast<Header*>(reinterpret_cast<const Header*>(data));

			// data size must be >= header + length value.
			if (sizeof(uint8_t) * 2 + header->length > len)
			{
				MS_WARN_TAG(rtcp, "not enough space for SDES item, discarded");

				return nullptr;
			}
```

It assumes that `data + len` can hold a `Header` struct, but it's not true if `len` is less than `sizeof(Header)`. So when calling this `SdesItem::Parse()` function from line 128 it crashes:

```c++
while (len > offset)
{
	SdesItem* item = SdesItem::Parse(data + offset, len - offset);
```

Well, not so sure now...

**Comment by ibc** [comment]
I think the same would happen in:

```c++
SdesPacket* SdesPacket::Parse(const uint8_t* data, size_t len)
		{
			MS_TRACE();

			// Get the header.
			auto* header = const_cast<CommonHeader*>(reinterpret_cast<const CommonHeader*>(data));
			std::unique_ptr<SdesPacket> packet(new SdesPacket());
			size_t offset = sizeof(Packet::CommonHeader);
			uint8_t count = header->count;

			while (((count--) != 0u) && (len > offset))
```

**Comment by ibc** [comment]
I think the initial issue is due to this:

In `SdesItem::Parse()`:

```c++
if (sizeof(uint8_t) * 2 + header->length > len)
```

It's checking `header->length` field before checking that there is space for the `Header` struct.
