### ISSUE TITLE
heap-buffer-overflow in RTCP::ReceiverReportPacket::Parse()

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#241]
* mediasoup 2.5.6

```
==7==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000169d7 at pc 0x0000009516d9 bp 0x7ffd3868d630 sp 0x7ffd3868d628
READ of size 1 at 0x6020000169d7 thread T0
    #0 0x9516d8 in Utils::Byte::Get4Bytes(unsigned char const*, unsigned long) /mediasoup/worker/out/../include/Utils.hpp:125:20
    #1 0xa38c03 in RTC::RTCP::ReceiverReportPacket::Parse(unsigned char const*, unsigned long, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/ReceiverReport.cpp:77:6
    #2 0xa260df in RTC::RTCP::Packet::Parse(unsigned char const*, unsigned long) /mediasoup/worker/out/../src/RTC/RTCP/Packet.cpp:97:17
    #3 0xb4946c in fuzz(unsigned char const*, unsigned long) /mediasoup/worker/out/../fuzzer/fuzzer.cpp:44:26
    #4 0xb4970a in LLVMFuzzerTestOneInput /mediasoup/worker/out/../fuzzer/fuzzer.cpp:63:2
    #5 0x45f47a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:576:15
    #6 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #7 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #8 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #9 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #10 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f6c1acdb82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x434a28 in _start (/mediasoup/worker/out/Release/mediasoup-worker-fuzzer+0x434a28)

0x6020000169d7 is located 3 bytes to the right of 4-byte region [0x6020000169d0,0x6020000169d4)
allocated by thread T0 here:
    #0 0x5951b2 in operator new[](unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:109:3
    #1 0x45f361 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:563:23
    #2 0x45eb95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
    #3 0x460fcb in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
    #4 0x461ca5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
    #5 0x4584f3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
    #6 0x4801d2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #7 0x7f6c1acdb82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /mediasoup/worker/out/../include/Utils.hpp:125:20 in Utils::Byte::Get4Bytes(unsigned char const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c047ffface0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fffacf0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fffad00: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fffad10: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c047fffad20: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
=>0x0c047fffad30: fa fa fd fd fa fa fd fd fa fa[04]fa fa fa fa fa
  0x0c047fffad40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffad50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffad60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffad70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffad80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==7==ABORTING
MS: 1 ChangeBinInt-; base unit: 6460a5205749f2bb887847a2beaa22dbf0da8ce8
0x90,0xc9,0x0,0x0,
\x90\xc9\x00\x00
artifact_prefix='./fuzzer/reports/'; Test unit written to ./fuzzer/reports/crash-6c9d53b6f28f874269f4488429b9c1fe923be4e2
Base64: kMkAAA==
```

IMHO here is the bug:

```c++
		ReceiverReportPacket* ReceiverReportPacket::Parse(const uint8_t* data, size_t len, size_t offset)
		{
			MS_TRACE();

			// Get the header.
			auto* header = const_cast<CommonHeader*>(reinterpret_cast<const CommonHeader*>(data));
			std::unique_ptr<ReceiverReportPacket> packet(new ReceiverReportPacket());

			packet->SetSsrc(
			  Utils::Byte::Get4Bytes(reinterpret_cast<uint8_t*>(header), sizeof(CommonHeader)));
```

It's reading 4 bytes starting from `data` but it does not verify that `len >= 4`.

**Comment by ibc** [comment]
May be fixed in 84dcd22aad2ce1bb1cc4fc5528e9be9efd605b91.

**Comment by jmillan** [comment]
shall we then close this issue?

**Comment by ibc** [comment]
yes, closed
