### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by chamikara1998** [versatica/mediasoup#375]
Mediasoup npm install failed. Tried on Mac OS X Mojave and centos system. both failed.
I also updated python => python 3 
gcc => 9.1
make => GNU Make 3.82

This is the result of centos 7.0

`Traceback (most recent call last):
  File "./scripts/configure.py", line 111, in <module>
    run_gyp(gyp_args)
  File "./scripts/configure.py", line 49, in run_gyp
    rc = gyp.main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./deps/gyp/pylib/gyp/generator/make.py", line 2210, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "./deps/gyp/pylib/gyp/generator/make.py", line 820, in Write
    self.Pchify))
  File "./deps/gyp/pylib/gyp/generator/make.py", line 1215, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 630, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 488, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 120, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 1409, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
make: *** [default] Error 1
`

then I tried with

`CC=gcc-9.1 npm install mediasoup`

then I got

`Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [default] Error 1
`

Please help me to solve this issue. Can I get a docker image for V3? I look forward to you as early as possible.

**Comment by ibc** [comment]
No, there is no "Docker image for mediasoup" because mediasoup is a library, not a standalone server.

Please paste versions. Why did you not honor the issue bug template? Closing issue. Open a new one by honoring the versions requested in the issue template.

**Comment by chamikara1998** [comment]
@ibc what do you mean by versions

**Comment by matinzd** [comment]
I have the same problem with installation through yarn and npm.

```
/server/node_modules/mediasoup/worker/out'
make: *** [Makefile:24: default] Error 2
```
