### ISSUE TITLE
Error installing package on latest version on CI server

### ISSUE THREAD

**Issue by r0zar** [versatica/mediasoup#543]
## Bug Report

I'm getting very strange results installing the latest version of mediasoup. Install times often take long or crash on some operating systems.

My CI server logs on a digital ocean "app" are included below. It's not clear to me what flavor or linux is running, but I can look into finding out if that is nessesary.

### Your environment

- Operating system: linux
- Node version: 14
- npm version: 7
- gcc/clang version: -
- mediasoup version: latest
- mediasoup-client version: -

### Issue description

```
11T01:52:40.789532724Z] => Initializing build
[2021-04-11T01:52:40.809660960Z] => Retrieving source code to /workspace
[2021-04-11T01:52:40.825542493Z] => Selecting branch "master"
[2021-04-11T01:52:41.404470717Z] => Checking out commit "499929e78316d4fb3875cafc8cdafb8c1103e3bb"
[2021-04-11T01:52:41.420674239Z] => Validating environment
[2021-04-11T01:52:41.455898931Z] 
[2021-04-11T01:52:41.455927333Z] => Building app using buildpacks
[2021-04-11T01:52:41.456811862Z] => Injecting app environment variables:
[2021-04-11T01:52:41.456829540Z]      TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN
[2021-04-11T01:52:41.601894383Z] => Running buildpack detection
[2021-04-11T01:52:41.601915846Z] 
[2021-04-11T01:52:42.129832976Z] 3 of 4 buildpacks participating
[2021-04-11T01:52:42.129934251Z] heroku/nodejs-engine  0.5.0
[2021-04-11T01:52:42.130076030Z] digitalocean/node     0.2.1
[2021-04-11T01:52:42.130179728Z] digitalocean/procfile 0.0.3
[2021-04-11T01:52:42.188861842Z] 
[2021-04-11T01:52:42.188890303Z] For documentation on the buildpacks used to build your app, please see:
[2021-04-11T01:52:42.188907314Z]    Node.js: https://do.co/apps-buildpack-node
[2021-04-11T01:52:42.190895111Z] 
[2021-04-11T01:52:42.190997153Z] => Checking for cache from a previous build
[2021-04-11T01:52:45.006108229Z] Restoring metadata for "heroku/nodejs-engine:nodejs" from app image
[2021-04-11T01:52:45.007321913Z] Restoring metadata for "heroku/nodejs-engine:yarn" from app image
[2021-04-11T01:52:45.008262119Z] Restoring metadata for "heroku/nodejs-engine:toolbox" from cache
[2021-04-11T01:52:45.009697198Z] Restoring metadata for "digitalocean/node:node_modules" from cache
[2021-04-11T01:52:46.411014605Z] Restoring data for "heroku/nodejs-engine:nodejs" from cache
[2021-04-11T01:52:46.412038204Z] Restoring data for "heroku/nodejs-engine:toolbox" from cache
[2021-04-11T01:52:46.413369646Z] Restoring data for "heroku/nodejs-engine:yarn" from cache
[2021-04-11T01:52:46.415713282Z] Restoring data for "digitalocean/node:node_modules" from cache
[2021-04-11T01:52:50.745963184Z] 
[2021-04-11T01:52:50.746139133Z] => Building app
[2021-04-11T01:52:50.746231102Z] 
[2021-04-11T01:52:50.874896359Z] ---> Node.js Buildpack
[2021-04-11T01:52:50.885166053Z] ---> Installing toolbox
[2021-04-11T01:52:50.898474979Z] ---> Getting Node version
[2021-04-11T01:52:50.917981285Z] ---> Resolving Node version
[2021-04-11T01:52:51.446919875Z] ---> Reusing Node v12.22.1
[2021-04-11T01:52:51.446943022Z] ---> Parsing package.json
[2021-04-11T01:52:51.787118449Z] ---> No file to start server
[2021-04-11T01:52:51.787147700Z] ---> either use 'docker run' to start container or add index.js or server.js
[2021-04-11T01:52:51.812329342Z] Installing node_modules using npm (from package-lock.json)
[2021-04-11T01:53:13.038428331Z] 
[2021-04-11T01:53:13.038464262Z] > clang-tools-prebuilt@0.1.4 postinstall /workspace/node_modules/clang-tools-prebuilt
[2021-04-11T01:53:13.038470952Z] > node install.js
[2021-04-11T01:53:13.038474462Z] 
Downloading clang-tools-r298696-linux.tgz
[2021-04-11T01:53:14.799804854Z] [============================================>] 100.0% of 40.98 MB (23.41 MB/s)
[2021-04-11T01:53:14.801194983Z] unziping /home/apps/.clang-tools/clang-tools-r298696-linux.tgz
[2021-04-11T01:53:16.228934396Z] 
[2021-04-11T01:53:16.228961492Z] > mediasoup@3.7.1 postinstall /workspace/node_modules/mediasoup
[2021-04-11T01:53:16.228971922Z] > node npm-scripts.js postinstall
[2021-04-11T01:53:16.228978619Z] 
[2021-04-11T01:53:16.363000547Z] npm-scripts.js [INFO] running task "postinstall"
[2021-04-11T01:53:16.363637323Z] npm-scripts.js [INFO] executing command: make -C worker
[2021-04-11T01:53:16.392731141Z] make: Entering directory '/workspace/node_modules/mediasoup/worker'
[2021-04-11T01:53:16.461300038Z] /usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
[2021-04-11T01:53:16.761274741Z] Traceback (most recent call last):
[2021-04-11T01:53:16.761321343Z]   File "./scripts/configure.py", line 112, in <module>
[2021-04-11T01:53:16.761330613Z]     run_gyp(gyp_args)
[2021-04-11T01:53:16.761615934Z] ['-R', 'mediasoup-worker', '/workspace/node_modules/mediasoup/worker/mediasoup-worker.gyp', '-I', '/workspace/node_modules/mediasoup/worker/common.gypi', '--depth=.', '-f', 'make', '-Goutput_dir=/workspace/node_modules/mediasoup/worker/out', '--generator-output', '/workspace/node_modules/mediasoup/worker/out', '-Dgcc_version=75', '-Dclang=0', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
[2021-04-11T01:53:16.761841751Z]   File "./scripts/configure.py", line 50, in run_gyp
[2021-04-11T01:53:16.762006846Z]     rc = gyp.main(args)
[2021-04-11T01:53:16.762401772Z]   File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main
[2021-04-11T01:53:16.763193294Z]     return gyp_main(args)
[2021-04-11T01:53:16.763212650Z]   File "./deps/gyp/pylib/gyp/__init__.py", line 521, in gyp_main
[2021-04-11T01:53:16.763346510Z]     options.duplicate_basename_check)
[2021-04-11T01:53:16.763371407Z]   File "./deps/gyp/pylib/gyp/__init__.py", line 137, in Load
[2021-04-11T01:53:16.764052191Z]     params['parallel'], params['root_targets'])
[2021-04-11T01:53:16.764071174Z]   File "./deps/gyp/pylib/gyp/input.py", line 2783, in Load
[2021-04-11T01:53:16.765172980Z]     check, generator_input_info)
[2021-04-11T01:53:16.765197283Z]   File "./deps/gyp/pylib/gyp/input.py", line 611, in LoadTargetBuildFilesParallel
[2021-04-11T01:53:16.765875998Z]     parallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())
[2021-04-11T01:53:16.765896707Z]   File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
[2021-04-11T01:53:16.766000211Z]     return Pool(processes, initializer, initargs, maxtasksperchild)
[2021-04-11T01:53:16.766181860Z]   File "/usr/lib/python2.7/multiprocessing/pool.py", line 140, in __init__
[2021-04-11T01:53:16.766496810Z]     self._setup_queues()
[2021-04-11T01:53:16.767059405Z]   File "/usr/lib/python2.7/multiprocessing/pool.py", line 236, in _setup_queues
[2021-04-11T01:53:16.767425682Z]     self._inqueue = SimpleQueue()
[2021-04-11T01:53:16.767437020Z]   File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
[2021-04-11T01:53:16.767713808Z]     self._rlock = Lock()
[2021-04-11T01:53:16.767719358Z]   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
[2021-04-11T01:53:16.767723921Z]     SemLock.__init__(self, SEMAPHORE, 1, 1)
[2021-04-11T01:53:16.767729724Z]   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
[2021-04-11T01:53:16.768475858Z]     sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
[2021-04-11T01:53:16.768490837Z] OSError: [Errno 38] Function not implemented
[2021-04-11T01:53:16.776695048Z] make: *** [default] Error 1
[2021-04-11T01:53:16.776820028Z] Makefile:24: recipe for target 'default' failed
[2021-04-11T01:53:16.776834273Z] make: Leaving directory '/workspace/node_modules/mediasoup/worker'
[2021-04-11T01:53:16.812977169Z] npm ERR! code ELIFECYCLE
[2021-04-11T01:53:16.813650045Z] npm ERR! errno 1
[2021-04-11T01:53:16.825334457Z] npm ERR! mediasoup@3.7.1 postinstall: `node npm-scripts.js postinstall`
[2021-04-11T01:53:16.825614352Z] npm ERR! Exit status 1
[2021-04-11T01:53:16.825754371Z] npm ERR! 
[2021-04-11T01:53:16.826045879Z] npm ERR! Failed at the mediasoup@3.7.1 postinstall script.
[2021-04-11T01:53:16.826154991Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2021-04-11T01:53:16.843295495Z] 
[2021-04-11T01:53:16.843478596Z] npm ERR! A complete log of this run can be found in:
[2021-04-11T01:53:16.843711138Z] npm ERR!     /home/apps/.npm/_logs/2021-04-11T01_53_16_835Z-debug.log
[2021-04-11T01:53:16.870634416Z] unable to invoke layer creator
[2021-04-11T01:53:16.870654083Z] installing node_modules: exit status 1
[2021-04-11T01:53:16.873535974Z] ERROR: failed to build: exit status 1
[2021-04-11T01:53:16.933716458Z] 
[2021-04-11T01:53:16.933760756Z] For documentation on the buildpacks used to build your app, please see:
[2021-04-11T01:53:16.933854177Z]    Node.js: https://do.co/apps-buildpack-node
[2021-04-11T01:53:16.935798266Z] 
[2021-04-11T01:53:16.936481623Z]  ! Build failed (145)
[]
```

**Comment by r0zar** [comment]
I was able to solve the issue locally by setting the
`MEDIASOUP_MAX_CORES` env var during the npm install.

I believe it was detecting my CPU's 32 core upper limit, and overheating my CPU during the build process, causing my computer to emergency shutdown. oof.

**Comment by ibc** [comment]
This seems to be a problem in your environment related to Python so this may be a problem  with gyp. However we are gonna migrate to CMake so we cannot fix this. Please ask in the forum in case someone knows about this.

**Comment by r0zar** [comment]
Ok, I'll look into what options i have for making sure it has all the required dependencies. thanks
