### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by chennasi** [versatica/mediasoup#740]
Microsoft Windows [Version 10.0.22000.376]
(c) Microsoft Corporation. All rights reserved.

C:\Users\chenn\Desktop\mediasoup-3>npm install
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

> mediasoup@3.9.2 postinstall
  /usr/bin/python3.exe -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python3.exe -m pip install [options] [-e] <local project path> ...
  /usr/bin/python3.exe -m pip install [options] <archive url/path> ...

no such option: --system
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting setuptools
  Using cached setuptools-60.0.3-py3-none-any.whl (952 kB)
Installing collected packages: setuptools, pip     Successfully installed pip-21.3.1 setuptools-60.0.3
/usr/bin/python3 -m pip install --upgrade --target=\out/pip  meson ninja
Collecting meson
  Using cached meson-0.60.2-py3-none-any.whl (838 kB)
Collecting ninja
  Using cached ninja-1.10.2.3.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ninja
  Building wheel for ninja (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.exe '/c/Users/chenn/Desktop/mediasoup-3/worker/\out/pip/pip/_vendor/pep517/in_process/_in_process.py' build_wheel /c/Users/chenn/AppData/Local/Temp/tmplsl2j7pu
       cwd: /c/Users/chenn/AppData/Local/Temp/pip-install-mnw7y0sy/ninja_4abbb9a8360545418297509edfe11025
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/c/Users/chenn/Desktop/mediasoup-3/worker/\out/pip/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/c/Users/chenn/Desktop/mediasoup-3/worker/\out/pip/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main  
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/c/Users/chenn/Desktop/mediasoup-3/worker/\out/pip/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 32, in <module>
      setup(
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 96, in __init__
      self.platform = get_platform()
    File "/c/Users/chenn/AppData/Local/Temp/pip-build-env-n50lc81v/overlay/lib/python3.9/site-packages/skbuild/platform_specifics/platform_factory.py", line 33, in get_platform       
      raise RuntimeError("Unsupported platform: {:s}. Please contact "
  RuntimeError: Unsupported platform: msys_nt-10.0-22000. Please contact the scikit-build team.
  ----------------------------------------
  ERROR: Failed building wheel for ninja
Failed to build ninja
ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects
make: *** [Makefile:61: meson-ninja] Error 1
make: Leaving directory '/c/Users/chenn/Desktop/mediasoup-3/worker'
npm ERR! code 1
npm ERR! path C:\Users\chenn\Desktop\mediasoup-3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node npm-scripts.js postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenn\AppData\Local\npm-cache\_logs\2021-12-22T12_07_34_897Z-debug-0.log

C:\Users\chenn\Desktop\mediasoup-3>
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system:
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version:
- mediasoup-client version:

**Comment by ibc** [comment]
If you open an issue again with the same data you will be banned.
