### ISSUE TITLE
run mediasoup demo, error: mediasoup/mediasoup-demo/server/node_modules/heapdump/index.js:16:15

### ISSUE THREAD

**Issue by chris-shenzhen-china** [versatica/mediasoup#772]
ubuntu20: run demo/server.js failed，cannot start worker process, 

at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/data/work/mediasoup/mediasoup-demo/server/node_modules/heapdump/index.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'

**Comment by chris-shenzhen-china** [comment]
done, reason: nodejs version not match.
