### ISSUE TITLE
Invalid or unexpected token on Logger.js:7

### ISSUE THREAD

**Issue by ndotie** [versatica/mediasoup#773]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

/home/ubuntu/smartchurch/node_modules/mediasoup/node/lib/Logger.js:7
    #debug;
    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/smartchurch/node_modules/mediasoup/node/lib/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

### Your environment

- Operating system: ubuntu 20.04
- Node version: 10.19.0
- npm version: 6.14.4
- gcc/clang version:
- mediasoup version: 3.9
- mediasoup-client version:

### after i install everything and start my node server that error pop up

inside node_modules/mediasoup/node/lib/Logger.js contnets
Object.defineProperty(exports, "__esModule", { value: true });
exports.Logger = void 0;
const debug_1 = require("debug");
const APP_NAME = 'mediasoup';
class Logger {
    #debug;
    #warn;
    #error;
    constructor(prefix) {
        if (prefix) {
            this.#debug = (0, debug_1.default)(`${APP_NAME}:${prefix}`);
            this.#warn = (0, debug_1.default)(`${APP_NAME}:WARN:${prefix}`);
            this.#error = (0, debug_1.default)(`${APP_NAME}:ERROR:${prefix}`);
        }
        else {
            this.#debug = (0, debug_1.default)(APP_NAME);
            this.#warn = (0, debug_1.default)(`${APP_NAME}:WARN`);
            this.#error = (0, debug_1.default)(`${APP_NAME}:ERROR`);
        }
        /* eslint-disable no-console */
        this.#debug.log = console.info.bind(console);
        this.#warn.log = console.warn.bind(console);

**Comment by ibc** [comment]
We write documentation for something:

https://mediasoup.org/documentation/v3/mediasoup/installation/#all-platforms

**Comment by ndotie** [comment]
i was running mediasoup on ubuntu with nodejs v 10, so the upgrade is something atleast node version 12 that resolved the problem
